site_name: Cities War Tutorials
site_description: Official game guide for Cities War
site_author: Game Dev Team
site_url: https://yourname.github.io/game-wiki/

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: black
    accent: grey
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

extra_css:
  - 'assets/styles/extra.css'

nav:
  - Getting Started: index.md
  - Cities:
      - Overview: cities/overview.md
      - Attributes: cities/attributes.md
      - City Infrastructure: cities/infrastructure.md
      - City Durability: cities/durability.md
      - Routes: cities/routes.md
      - Airports: cities/airports.md
      - Request: cities/request.md
  - Economy:
      - Resources: economy/resources.md
      - Gold: economy/gold.md
      - Gems: economy/gems.md
      - Market: economy/market.md
  - Units:
      - Armies: units/armies.md
      - Navies: units/navies.md
      - Air Forces: units/airforces.md
      - Missiles: units/missiles.md
  - Weapons:
      - Overview: weapons/overview.md
      - Firearm & Artillery: weapons/firearm.md
      - Tanks: weapons/tanks.md
      - Ships: weapons/ships.md
      - Aircraft: weapons/aircraft.md
      - Missiles: weapons/missiles.md
  - Alliances:
      - Overview: alliances/overview.md
      - Alliance Capital: alliances/capital.md
      - Alliance Territory: alliances/territory.md
      - Regional War: alliances/regional.md
      - Top 100 Cities Tournament: alliances/top100.md
      - Rivalry: alliances/rivalry.md
      - Diplomacy: alliances/diplomacy.md
      - Alliance Bank: alliances/bank.md
      - Alliance Hierarchy: alliances/hierarchy.md
      - Alliance Levels: alliances/level.md
  - Wars & Conquest:
      - Combat System: wars/combat.md
      - Country: wars/country.md
      - Dominion: wars/dominion.md
      - Civilizations: wars/civilizations.md
  - General:
      - Player Levels: general/playerlevel.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - footnotes
  - def_list
